kind: pipeline
type: docker
name: Auto Build - main

steps:
- name: build
  image: node:lts
  commands:
  - npm config --location=global set registry https://registry.npmmirror.com/
  - npm install --location=global pnpm@8.1.1
  - pnpm install
  - pnpm build
  - du -h ./dist/*
  - du -h ./dist
  - mv dist react-template
  - tar -cvzf react-template.tar.gz react-template

trigger:
  branch:
  - main
