kind: pipeline
type: docker
name: Auto Build - main

steps:
  - name: build
    image: node:18.16.1
    commands:
      - npm config --location=global set registry https://registry.npmmirror.com/
      - npm install --location=global pnpm@8.6.0
      - pnpm install
      - pnpm build
      - du -h -d 1 ./dist/

trigger:
  branch:
    - main
