kind: pipeline
type: docker
name: Auto Build - main

steps:
  - name: build
    image: node:lts
    volumes:
      - name: cache
        path: /drone/.pnpm-store
    commands:
      - npm config --location=global set registry https://registry.npmmirror.com/
      - npm install --location=global pnpm@8.6.0
      - pnpm config set store-dir /drone/.pnpm-store
      - pnpm install
      - pnpm build
      - du -h ./dist/*
      - du -h ./dist
      - mv dist react-template
      - tar -cvzf react-template.tar.gz react-template
      - du -h react-template.tar.gz

volumes:
  - name: cache
    host:
      path: /tmp/pnpm_cache

trigger:
  branch:
    - main
