kind: pipeline
type: docker
name: default

steps:
- name: hello
  image: node:lts
  commands:
  - npm config --location=global set registry https://registry.npmmirror.com/
  - npm install --location=global pnpm@8.1.1
  - pnpm install
  - pnpm build
  - du -h ./dist/*

trigger:
  branch:
  - master
